### ISSUE TITLE
missing negative sign

### ISSUE THREAD

**Issue by hehoffmann** [dl4nlp-tuda/deep-learning-for-nlp-lectures#26]
I may be wrong, but I think there is a negative sign missing before the sum sign, right?

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/7b65e257e28fc42df16873a233255ff7b87e7afd/latex/lecture02/dl4nlp2022-lecture02.tex#L1012

**Comment by habernal** [comment]
Good catch, indeed! Thanks
