### ISSUE TITLE
Wrong values after activation

### ISSUE THREAD

**Issue by hehoffmann** [dl4nlp-tuda/deep-learning-for-nlp-lectures#27]
I believe that these values are wrong:
Before activation the values should be [1,1,1/3,1] and after [0.28, 0.28, 0.15, 0.28].
(analogously the solutions of y_hat,2 and y_hat,3).

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/d6d6665407c567b3cff9f7e70e533519e679bf8d/latex/lecture07/rnn.tex#L259

**Comment by habernal** [comment]
Thanks for spotting this! I forgot to commit the 2022 latex sources, so now the actual line is

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/17d1a4211567cac02e9c280022b1d66047ec3c0d/latex/lecture07/dl4nlp2022-lecture07.tex#L423

**Comment by hehoffmann** [comment]
But the corresponding in person lecture slides are still wrong (in person 2022 lecture 7 page 12). This is what I actually meant. I was just trying to find the corresponding lines.

And I think the problem I tried to explaniere is still there. The values don't match the expected ones for pre or post activation.

**Comment by habernal** [comment]
I've kept the original file unchanged but now the fixed PDF is linked from the main page

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/main/pdf/dl4nlp2022-lecture07-with-fixed-issues.pdf

Is that right?

**Comment by hehoffmann** [comment]
In my opinion, this should now be correct 👍
