### ISSUE TITLE
lecture 4, slide 39: cosine similarity 

### ISSUE THREAD

**Issue by kathath** [dl4nlp-tuda/deep-learning-for-nlp-lectures#31]
In lecture 2 the cosine similarity is defined as follows:
![cosine_sim](https://user-images.githubusercontent.com/74715925/178535229-a68b9a24-5c18-4f95-87b7-56db3dfdf77e.png)

Therefore, I assume that the two squares in the denominator on slide 39 in lecture 4 are probably wrong:
![question](https://user-images.githubusercontent.com/74715925/178539281-0555c14a-b3b5-4b85-9f30-8b41c9af696c.png)

Because if I understand correctly, the similarity value of two words is the cosine similarity of the word embeddings.

**Comment by habernal** [comment]
Good catch! Although it's just sloppy math -- L2 norm can be written with the 2 index, but this looks like a power 2. Fixed with \norm for better clarity.
