### ISSUE TITLE
Fix formula for 1-D convolution operation (lecture 6, slide 5)

### ISSUE THREAD

**Issue by SebOchs** [dl4nlp-tuda/deep-learning-for-nlp-lectures#32]
In the formula, g[m] should be g[m+M], so that the correct value of the filter is accessed, e.g. g[0] (as first access) instead of g[-2], for window size M=2.

The same step may need to be applied to slide 8 as well (g[m, n] --> g[m+M, n+N])

**Comment by habernal** [comment]
In fact, there's multiple issues with the formula (relying on some implicit assumptions, such as that the sums are from -infty to infty but we assume zero values except for the observed "image"), which are then somehow clear in the actual example. This needs to be a bit reworked for next year to be precise; refs. Goodfellow et al., p. 332 (generic conv. coming from integration), or Goldberg, p. 153 (which is better but needs to introduce the specific notation).

**Comment by habernal** [comment]
We'll not cover CNNs from 2023 anymore
