### ISSUE TITLE
Is Sigmoid an odd function? 

### ISSUE THREAD

**Issue by muhammed-shihebi** [dl4nlp-tuda/deep-learning-for-nlp-lectures#44]
In the following line in lecture 3, it is mentioned that Sigmoid is an "odd function": 

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/2b2a82fad1a1e17acb917c9d6fadea93aa7a6b0e/latex/lecture03/dl4nlp2023-lecture03.tex#L824

I am not sure if you mean "odd" as "weird" or a mathematically odd function that satisfies the condition f(-x) = -f(x) because at least it appears that Sigmoid is not mathematically odd. 

Example: 

$\sigma(-0.4) = 0.4013$
$-\sigma(0.4) = -0.5987$

**Comment by habernal** [comment]
Good catch. It's not "odd" - it's symmetric like an odd function, but not symmetric over [0, 0].
