### ISSUE TITLE
Wrong subtitle in Lecture 06 and 07

### ISSUE THREAD

**Issue by long21wt** [dl4nlp-tuda/deep-learning-for-nlp-lectures#48]
https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/5193ce80f076f95f7ed56ef954e75547cc475b63/latex/lecture06/dl4nlp2023-lecture06.tex#L116

https://github.com/dl4nlp-tuda/deep-learning-for-nlp-lectures/blob/5193ce80f076f95f7ed56ef954e75547cc475b63/latex/lecture07/dl4nlp2023-lecture07.tex#L123

**Comment by habernal** [comment]
Thanks!
