### ISSUE TITLE
Lecture 7, Gated Architectures

### ISSUE THREAD

**Issue by mihlefeld** [dl4nlp-tuda/deep-learning-for-nlp-lectures#49]
There is an error in the equation on slide 20 and following:
s' <- g * x + (1 + g) * s
instead it should be 
s' <- g * x + (1 - g) * s
Otherwise we would read all values of s

**Comment by habernal** [comment]
But in modulo 2, 1 + 1 and 1 - 1 are the same, aren't they?

**Comment by mihlefeld** [comment]
Yes, but in reality g is not in {0, 1} but a real number between 0 and 1 right? So i think it would be less confusing if it were 1-g

**Comment by habernal** [comment]
OK, that makes sense

**Comment by Danghor** [comment]
I proposed the same change in #54. However, I have not considered that we work in module 2 here.
If the equation is kept the same, I think a hint on the slide that we work in modulo 2 and `+` and `-` work the same in this case would help students like us :)

**Comment by habernal** [comment]
Closed in 5a60cd2
